///************************************************
/// Generated by: haihd
/// Date: 21/08/2015 03:34:25
/// Goal: Create User Service Class for DM_BAO_HIEM
///************************************************
/// <summary>
/// Create User Service Class for DM_BAO_HIEM
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_DM_BAO_HIEM : US_Object
{
	private const string c_TableName = "DM_BAO_HIEM";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strTEN_BH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_BH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_BH"] = value;
		}
	}

	public bool IsTEN_BHNull() 
	{
		return pm_objDR.IsNull("TEN_BH");
	}

	public void SetTEN_BHNull() {
		pm_objDR["TEN_BH"] = System.Convert.DBNull;
	}

	public string strMA_BH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_BH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_BH"] = value;
		}
	}

	public bool IsMA_BHNull() 
	{
		return pm_objDR.IsNull("MA_BH");
	}

	public void SetMA_BHNull() {
		pm_objDR["MA_BH"] = System.Convert.DBNull;
	}

	public decimal dcTI_LE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TI_LE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TI_LE"] = value;
		}
	}

	public bool IsTI_LENull()	{
		return pm_objDR.IsNull("TI_LE");
	}

	public void SetTI_LENull() {
		pm_objDR["TI_LE"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_BAO_HIEM() 
	{
		pm_objDS = new DS_DM_BAO_HIEM();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_BAO_HIEM(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_BAO_HIEM(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_BAO_HIEM();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
