///************************************************
/// Generated by: haihd
/// Date: 17/08/2015 07:11:28
/// Goal: Create User Service Class for DM_HE_SO_LUONG_NS
///************************************************
/// <summary>
/// Create User Service Class for DM_HE_SO_LUONG_NS
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_DM_HE_SO_LUONG_NS : US_Object
{
	private const string c_TableName = "DM_HE_SO_LUONG_NS";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_MA_LNS 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_MA_LNS", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_MA_LNS"] = value;
		}
	}

	public bool IsID_MA_LNSNull()	{
		return pm_objDR.IsNull("ID_MA_LNS");
	}

	public void SetID_MA_LNSNull() {
		pm_objDR["ID_MA_LNS"] = System.Convert.DBNull;
	}

	public decimal dcID_MUC_LNS 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_MUC_LNS", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_MUC_LNS"] = value;
		}
	}

	public bool IsID_MUC_LNSNull()	{
		return pm_objDR.IsNull("ID_MUC_LNS");
	}

	public void SetID_MUC_LNSNull() {
		pm_objDR["ID_MUC_LNS"] = System.Convert.DBNull;
	}

	public decimal dcHE_SO 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "HE_SO", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["HE_SO"] = value;
		}
	}

	public bool IsHE_SONull()	{
		return pm_objDR.IsNull("HE_SO");
	}

	public void SetHE_SONull() {
		pm_objDR["HE_SO"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_LAO_DONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_LAO_DONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_LAO_DONG"] = value;
		}
	}

	public bool IsID_LOAI_LAO_DONGNull()	{
		return pm_objDR.IsNull("ID_LOAI_LAO_DONG");
	}

	public void SetID_LOAI_LAO_DONGNull() {
		pm_objDR["ID_LOAI_LAO_DONG"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_HE_SO_LUONG_NS() 
	{
		pm_objDS = new DS_DM_HE_SO_LUONG_NS();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_HE_SO_LUONG_NS(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_HE_SO_LUONG_NS(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_HE_SO_LUONG_NS();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


    public void FillDatasetTheoIDMaMuc(DS_DM_HE_SO_LUONG_NS v_ds, string id_ma_lns, string id_muc_lns)
    {
        CStoredProc v_cstore = new CStoredProc("pr_LNS_get_he_so_theo_ID_ma_muc");
        v_cstore.addDecimalInputParam("@id_ma_lns", id_ma_lns);
        v_cstore.addDecimalInputParam("@id_muc_lns", id_muc_lns);
        v_cstore.fillDataSetByCommand(this, v_ds);
    }
}
}
