///************************************************
/// Generated by: THAIPH
/// Date: 11/12/2015 08:46:20
/// Goal: Create User Service Class for GD_PHU_THUOC_DETAILS
///************************************************
/// <summary>
/// Create User Service Class for GD_PHU_THUOC_DETAILS
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US
{

public class US_GD_PHU_THUOC_DETAILS : US_Object
{
	private const string c_TableName = "GD_PHU_THUOC_DETAILS";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_GD_PHU_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_GD_PHU_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_GD_PHU_THUOC"] = value;
		}
	}

	public bool IsID_GD_PHU_THUOCNull()	{
		return pm_objDR.IsNull("ID_GD_PHU_THUOC");
	}

	public void SetID_GD_PHU_THUOCNull() {
		pm_objDR["ID_GD_PHU_THUOC"] = System.Convert.DBNull;
	}

	public string strTEN_NGUOI_PHU_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NGUOI_PHU_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NGUOI_PHU_THUOC"] = value;
		}
	}

	public bool IsTEN_NGUOI_PHU_THUOCNull() 
	{
		return pm_objDR.IsNull("TEN_NGUOI_PHU_THUOC");
	}

	public void SetTEN_NGUOI_PHU_THUOCNull() {
		pm_objDR["TEN_NGUOI_PHU_THUOC"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_SINH_NGUOI_PHU_THUOC
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_SINH_NGUOI_PHU_THUOC", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_SINH_NGUOI_PHU_THUOC"] = value;
		}
	}

	public bool IsNGAY_SINH_NGUOI_PHU_THUOCNull()
	{
		return pm_objDR.IsNull("NGAY_SINH_NGUOI_PHU_THUOC");
	}

	public void SetNGAY_SINH_NGUOI_PHU_THUOCNull()
	{
		pm_objDR["NGAY_SINH_NGUOI_PHU_THUOC"] = System.Convert.DBNull;
	}

	public string strSO_CMT_NGUOI_PHU_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_CMT_NGUOI_PHU_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_CMT_NGUOI_PHU_THUOC"] = value;
		}
	}

	public bool IsSO_CMT_NGUOI_PHU_THUOCNull() 
	{
		return pm_objDR.IsNull("SO_CMT_NGUOI_PHU_THUOC");
	}

	public void SetSO_CMT_NGUOI_PHU_THUOCNull() {
		pm_objDR["SO_CMT_NGUOI_PHU_THUOC"] = System.Convert.DBNull;
	}

	public string strMA_SO_THUE_NGUOI_PHU_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_SO_THUE_NGUOI_PHU_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_SO_THUE_NGUOI_PHU_THUOC"] = value;
		}
	}

	public bool IsMA_SO_THUE_NGUOI_PHU_THUOCNull() 
	{
		return pm_objDR.IsNull("MA_SO_THUE_NGUOI_PHU_THUOC");
	}

	public void SetMA_SO_THUE_NGUOI_PHU_THUOCNull() {
		pm_objDR["MA_SO_THUE_NGUOI_PHU_THUOC"] = System.Convert.DBNull;
	}

	public string strQUAN_HE_VOI_NGUOI_NOP_THUE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "QUAN_HE_VOI_NGUOI_NOP_THUE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["QUAN_HE_VOI_NGUOI_NOP_THUE"] = value;
		}
	}

	public bool IsQUAN_HE_VOI_NGUOI_NOP_THUENull() 
	{
		return pm_objDR.IsNull("QUAN_HE_VOI_NGUOI_NOP_THUE");
	}

	public void SetQUAN_HE_VOI_NGUOI_NOP_THUENull() {
		pm_objDR["QUAN_HE_VOI_NGUOI_NOP_THUE"] = System.Convert.DBNull;
	}

	public string strDIA_CHI_NGUOI_PHU_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_CHI_NGUOI_PHU_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_CHI_NGUOI_PHU_THUOC"] = value;
		}
	}

	public bool IsDIA_CHI_NGUOI_PHU_THUOCNull() 
	{
		return pm_objDR.IsNull("DIA_CHI_NGUOI_PHU_THUOC");
	}

	public void SetDIA_CHI_NGUOI_PHU_THUOCNull() {
		pm_objDR["DIA_CHI_NGUOI_PHU_THUOC"] = System.Convert.DBNull;
	}

	public string strGIAY_TO_DI_KEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GIAY_TO_DI_KEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GIAY_TO_DI_KEM"] = value;
		}
	}

	public bool IsGIAY_TO_DI_KEMNull() 
	{
		return pm_objDR.IsNull("GIAY_TO_DI_KEM");
	}

	public void SetGIAY_TO_DI_KEMNull() {
		pm_objDR["GIAY_TO_DI_KEM"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_LAP
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_LAP", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_LAP"] = value;
		}
	}

	public bool IsNGAY_LAPNull()
	{
		return pm_objDR.IsNull("NGAY_LAP");
	}

	public void SetNGAY_LAPNull()
	{
		pm_objDR["NGAY_LAP"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_SUA
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_SUA", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_SUA"] = value;
		}
	}

	public bool IsNGAY_SUANull()
	{
		return pm_objDR.IsNull("NGAY_SUA");
	}

	public void SetNGAY_SUANull()
	{
		pm_objDR["NGAY_SUA"] = System.Convert.DBNull;
	}

	public string strNGUOI_LAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_LAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_LAP"] = value;
		}
	}

	public bool IsNGUOI_LAPNull() 
	{
		return pm_objDR.IsNull("NGUOI_LAP");
	}

	public void SetNGUOI_LAPNull() {
		pm_objDR["NGUOI_LAP"] = System.Convert.DBNull;
	}

	public string strNGUOI_SUA 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_SUA", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_SUA"] = value;
		}
	}

	public bool IsNGUOI_SUANull() 
	{
		return pm_objDR.IsNull("NGUOI_SUA");
	}

	public void SetNGUOI_SUANull() {
		pm_objDR["NGUOI_SUA"] = System.Convert.DBNull;
	}

	public string strDA_XOA 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DA_XOA", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DA_XOA"] = value;
		}
	}

	public bool IsDA_XOANull() 
	{
		return pm_objDR.IsNull("DA_XOA");
	}

	public void SetDA_XOANull() {
		pm_objDR["DA_XOA"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_PHU_THUOC_DETAILS() 
	{
		pm_objDS = new DS_GD_PHU_THUOC_DETAILS();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_PHU_THUOC_DETAILS(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_PHU_THUOC_DETAILS(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_PHU_THUOC_DETAILS();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
