///************************************************
/// Generated by: tuyennt
/// Date: 04-03-2016 05:22:07
/// Goal: Create User Service Class for GD_QUY_THU_NHAP_KHAC
///************************************************
/// <summary>
/// Create User Service Class for GD_QUY_THU_NHAP_KHAC
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_GD_QUY_THU_NHAP_KHAC : US_Object
{
	private const string c_TableName = "GD_QUY_THU_NHAP_KHAC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strTEN_QUY 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_QUY", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_QUY"] = value;
		}
	}

	public bool IsTEN_QUYNull() 
	{
		return pm_objDR.IsNull("TEN_QUY");
	}

	public void SetTEN_QUYNull() {
		pm_objDR["TEN_QUY"] = System.Convert.DBNull;
	}

	public string strTHANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "THANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["THANG"] = value;
		}
	}

	public bool IsTHANGNull() 
	{
		return pm_objDR.IsNull("THANG");
	}

	public void SetTHANGNull() {
		pm_objDR["THANG"] = System.Convert.DBNull;
	}

	public string strNAM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NAM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NAM"] = value;
		}
	}

	public bool IsNAMNull() 
	{
		return pm_objDR.IsNull("NAM");
	}

	public void SetNAMNull() {
		pm_objDR["NAM"] = System.Convert.DBNull;
	}

	public string strNGUOI_LAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_LAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_LAP"] = value;
		}
	}

	public bool IsNGUOI_LAPNull() 
	{
		return pm_objDR.IsNull("NGUOI_LAP");
	}

	public void SetNGUOI_LAPNull() {
		pm_objDR["NGUOI_LAP"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_LAP
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_LAP", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_LAP"] = value;
		}
	}

	public bool IsNGAY_LAPNull()
	{
		return pm_objDR.IsNull("NGAY_LAP");
	}

	public void SetNGAY_LAPNull()
	{
		pm_objDR["NGAY_LAP"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_LAP_PHAN_MEM
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_LAP_PHAN_MEM", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_LAP_PHAN_MEM"] = value;
		}
	}

	public bool IsNGAY_LAP_PHAN_MEMNull()
	{
		return pm_objDR.IsNull("NGAY_LAP_PHAN_MEM");
	}

	public void SetNGAY_LAP_PHAN_MEMNull()
	{
		pm_objDR["NGAY_LAP_PHAN_MEM"] = System.Convert.DBNull;
	}

	public string strNGUOI_LAP_PHAN_MEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_LAP_PHAN_MEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_LAP_PHAN_MEM"] = value;
		}
	}

	public bool IsNGUOI_LAP_PHAN_MEMNull() 
	{
		return pm_objDR.IsNull("NGUOI_LAP_PHAN_MEM");
	}

	public void SetNGUOI_LAP_PHAN_MEMNull() {
		pm_objDR["NGUOI_LAP_PHAN_MEM"] = System.Convert.DBNull;
	}

	public DateTime datTU_NGAY_XET_THUONG
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "TU_NGAY_XET_THUONG", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["TU_NGAY_XET_THUONG"] = value;
		}
	}

	public bool IsTU_NGAY_XET_THUONGNull()
	{
		return pm_objDR.IsNull("TU_NGAY_XET_THUONG");
	}

	public void SetTU_NGAY_XET_THUONGNull()
	{
		pm_objDR["TU_NGAY_XET_THUONG"] = System.Convert.DBNull;
	}

	public DateTime datDEN_NGAY_XET_THUONG
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "DEN_NGAY_XET_THUONG", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["DEN_NGAY_XET_THUONG"] = value;
		}
	}

	public bool IsDEN_NGAY_XET_THUONGNull()
	{
		return pm_objDR.IsNull("DEN_NGAY_XET_THUONG");
	}

	public void SetDEN_NGAY_XET_THUONGNull()
	{
		pm_objDR["DEN_NGAY_XET_THUONG"] = System.Convert.DBNull;
	}

	public string strLY_DO_THUONG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "LY_DO_THUONG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["LY_DO_THUONG"] = value;
		}
	}

	public bool IsLY_DO_THUONGNull() 
	{
		return pm_objDR.IsNull("LY_DO_THUONG");
	}

	public void SetLY_DO_THUONGNull() {
		pm_objDR["LY_DO_THUONG"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

	public string strDA_XOA 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DA_XOA", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DA_XOA"] = value;
		}
	}

	public bool IsDA_XOANull() 
	{
		return pm_objDR.IsNull("DA_XOA");
	}

	public void SetDA_XOANull() {
		pm_objDR["DA_XOA"] = System.Convert.DBNull;
	}

    public decimal dcID_LOAI_QUY_THU_NHAP_KHAC
    {
        get
        {
            return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_QUY_THU_NHAP_KHAC", IPConstants.c_DefaultDecimal);
        }
        set
        {
            pm_objDR["ID_LOAI_QUY_THU_NHAP_KHAC"] = value;
        }
    }

    public bool IsID_LOAI_QUY_THU_NHAP_KHACNull()
    {
        return pm_objDR.IsNull("ID_LOAI_QUY_THU_NHAP_KHAC");
    }

    public void SetID_LOAI_QUY_THU_NHAP_KHACNull()
    {
        pm_objDR["ID_LOAI_QUY_THU_NHAP_KHAC"] = System.Convert.DBNull;
    }

    public decimal dcID_CACH_QUYET_TOAN
    {
        get
        {
            return CNull.RowNVLDecimal(pm_objDR, "ID_CACH_QUYET_TOAN", IPConstants.c_DefaultDecimal);
        }
        set
        {
            pm_objDR["ID_CACH_QUYET_TOAN"] = value;
        }
    }

    public bool IsID_CACH_QUYET_TOANNull()
    {
        return pm_objDR.IsNull("ID_CACH_QUYET_TOAN");
    }

    public void SetID_CACH_QUYET_TOANNull()
    {
        pm_objDR["ID_CACH_QUYET_TOAN"] = System.Convert.DBNull;
    }
#endregion
#region "Init Functions"
	public US_GD_QUY_THU_NHAP_KHAC() 
	{
		pm_objDS = new DS_GD_QUY_THU_NHAP_KHAC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_QUY_THU_NHAP_KHAC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_QUY_THU_NHAP_KHAC(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_QUY_THU_NHAP_KHAC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion

    public bool KiemTraQuyCoNhanVienChua(decimal ip_dc_id_quy, decimal ip_dc_id_nhan_vien)
    {
        CStoredProc v_obj = new CStoredProc("pr_TNK_nhan_vien_ton_tai_trong_quy_Check");

        v_obj.addDecimalInputParam("@ip_dc_id_quy_tien", ip_dc_id_quy);
        v_obj.addDecimalInputParam("@ip_dc_id_nhan_vien", ip_dc_id_nhan_vien);
        SqlParameter v_para_yn = v_obj.addNVarcharOutputParam("@op_yn", "");
        v_obj.ExecuteCommand(this);
        var v_bol_ket_qua = v_para_yn.Value.ToString() == "Y" ? true : false;
        return v_bol_ket_qua;
    }

    #region Additional
    public DataRow LayThongTinQuyThuNhapKhac(decimal ip_dc_id_quy_thu_nhap_khac)
    {
        CStoredProc v_pr = new CStoredProc("pr_TNK_thong_tin_quy_Get");
        v_pr.addDecimalInputParam("@ip_dc_id_quy_thu_nhap_khac", ip_dc_id_quy_thu_nhap_khac);

        DataSet v_ds_ouput = new DataSet();
        v_ds_ouput.Tables.Add();

        v_pr.fillDataSetByCommand(this, v_ds_ouput);
        return v_ds_ouput.Tables[0].Rows[0];
    }
    public DataTable LayChiTietQuy(decimal ip_dc_id_quy_thu_nhap_khac)
    {

        CStoredProc v_pr = new CStoredProc("pr_TNK_chi_tiet_quy_GetAll");
        v_pr.addDecimalInputParam("@ip_dc_id_quy_thu_nhap_khac", ip_dc_id_quy_thu_nhap_khac);

        DataSet v_ds_ouput = new DataSet();
        v_ds_ouput.Tables.Add();

        v_pr.fillDataSetByCommand(this, v_ds_ouput);
        return v_ds_ouput.Tables[0];
    }
    #endregion


    public void FillDatasetQuyTNKbyIDLoaiQuy(DS_GD_QUY_THU_NHAP_KHAC v_ds, decimal ip_id_loai_quy)
    {
        CStoredProc v_cstore = new CStoredProc("pr_TNK_quy_tien_GetTheoIDLoaiQuy");
        v_cstore.addDecimalInputParam("@id_loai_quy", ip_id_loai_quy);
        v_cstore.fillDataSetByCommand(this, v_ds);
    }

    public void FillDatasetQuyTNK(DS_GD_QUY_THU_NHAP_KHAC v_ds, DateTime ip_dat_tu_thang, DateTime ip_dat_den_thang)
    {
        CStoredProc v_cstore = new CStoredProc("pr_TNK_quy_tien_GetAll");
        v_cstore.addDatetimeInputParam("@ip_tu_thang", @ip_dat_tu_thang);
        v_cstore.addDatetimeInputParam("@ip_den_thang", @ip_dat_den_thang);
        v_cstore.fillDataSetByCommand(this, v_ds);
    }
}
}
