///************************************************
/// Generated by: tuyennt
/// Date: 12-04-2016 09:51:29
/// Goal: Create User Service Class for V_DM_DON_VI_2
///************************************************
/// <summary>
/// Create User Service Class for V_DM_DON_VI_2
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US
{

    public class US_V_DM_DON_VI_2 : US_Object
    {
        private const string c_TableName = "V_DM_DON_VI_2";
        #region "Public Properties"
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public string strTEN_DON_VI
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_DON_VI"] = value;
            }
        }

        public bool IsTEN_DON_VINull()
        {
            return pm_objDR.IsNull("TEN_DON_VI");
        }

        public void SetTEN_DON_VINull()
        {
            pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
        }

        public string strMA_DON_VI
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_DON_VI", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_DON_VI"] = value;
            }
        }

        public bool IsMA_DON_VINull()
        {
            return pm_objDR.IsNull("MA_DON_VI");
        }

        public void SetMA_DON_VINull()
        {
            pm_objDR["MA_DON_VI"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_DON_VI
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_DON_VI", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_DON_VI"] = value;
            }
        }

        public bool IsID_LOAI_DON_VINull()
        {
            return pm_objDR.IsNull("ID_LOAI_DON_VI");
        }

        public void SetID_LOAI_DON_VINull()
        {
            pm_objDR["ID_LOAI_DON_VI"] = System.Convert.DBNull;
        }

        public decimal dcID_DON_VI_CAP_TREN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_CAP_TREN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DON_VI_CAP_TREN"] = value;
            }
        }

        public bool IsID_DON_VI_CAP_TRENNull()
        {
            return pm_objDR.IsNull("ID_DON_VI_CAP_TREN");
        }

        public void SetID_DON_VI_CAP_TRENNull()
        {
            pm_objDR["ID_DON_VI_CAP_TREN"] = System.Convert.DBNull;
        }

        public decimal dcID_DV_0
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DV_0", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DV_0"] = value;
            }
        }

        public bool IsID_DV_0Null()
        {
            return pm_objDR.IsNull("ID_DV_0");
        }

        public void SetID_DV_0Null()
        {
            pm_objDR["ID_DV_0"] = System.Convert.DBNull;
        }

        public decimal dcID_DV_1
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DV_1", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DV_1"] = value;
            }
        }

        public bool IsID_DV_1Null()
        {
            return pm_objDR.IsNull("ID_DV_1");
        }

        public void SetID_DV_1Null()
        {
            pm_objDR["ID_DV_1"] = System.Convert.DBNull;
        }

        public decimal dcID_DV_2
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DV_2", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DV_2"] = value;
            }
        }

        public bool IsID_DV_2Null()
        {
            return pm_objDR.IsNull("ID_DV_2");
        }

        public void SetID_DV_2Null()
        {
            pm_objDR["ID_DV_2"] = System.Convert.DBNull;
        }

        public decimal dcID_DV_3
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DV_3", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DV_3"] = value;
            }
        }

        public bool IsID_DV_3Null()
        {
            return pm_objDR.IsNull("ID_DV_3");
        }

        public void SetID_DV_3Null()
        {
            pm_objDR["ID_DV_3"] = System.Convert.DBNull;
        }

        public decimal dcID_DV_4
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_DV_4", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_DV_4"] = value;
            }
        }

        public bool IsID_DV_4Null()
        {
            return pm_objDR.IsNull("ID_DV_4");
        }

        public void SetID_DV_4Null()
        {
            pm_objDR["ID_DV_4"] = System.Convert.DBNull;
        }

        public decimal dcTANG
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "TANG", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["TANG"] = value;
            }
        }

        public bool IsTANGNull()
        {
            return pm_objDR.IsNull("TANG");
        }

        public void SetTANGNull()
        {
            pm_objDR["TANG"] = System.Convert.DBNull;
        }

        public decimal dcSO_LUONG_NS_DANG_CONG_TAC
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG_NS_DANG_CONG_TAC", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["SO_LUONG_NS_DANG_CONG_TAC"] = value;
            }
        }

        public bool IsSO_LUONG_NS_DANG_CONG_TACNull()
        {
            return pm_objDR.IsNull("SO_LUONG_NS_DANG_CONG_TAC");
        }

        public void SetSO_LUONG_NS_DANG_CONG_TACNull()
        {
            pm_objDR["SO_LUONG_NS_DANG_CONG_TAC"] = System.Convert.DBNull;
        }

        #endregion
        #region "Init Functions"
        public US_V_DM_DON_VI_2()
        {
            pm_objDS = new DS_V_DM_DON_VI_2();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_V_DM_DON_VI_2(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_V_DM_DON_VI_2(decimal i_dbID)
        {
            pm_objDS = new DS_V_DM_DON_VI_2();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion
    }
}
