///************************************************
/// Generated by: HaiHD
/// Date: 07/01/2016 06:24:18
/// Goal: Create User Service Class for V_DM_TRANG_THAI_LAO_DONG
///************************************************
/// <summary>
/// Create User Service Class for V_DM_TRANG_THAI_LAO_DONG
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_V_DM_TRANG_THAI_LAO_DONG : US_Object
{
	private const string c_TableName = "V_DM_TRANG_THAI_LAO_DONG";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_TRANG_THAI_LD 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_TRANG_THAI_LD", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_TRANG_THAI_LD"] = value;
		}
	}

	public bool IsMA_TRANG_THAI_LDNull() 
	{
		return pm_objDR.IsNull("MA_TRANG_THAI_LD");
	}

	public void SetMA_TRANG_THAI_LDNull() {
		pm_objDR["MA_TRANG_THAI_LD"] = System.Convert.DBNull;
	}

	public string strTEN_TRANG_THAI_LD 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_TRANG_THAI_LD", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_TRANG_THAI_LD"] = value;
		}
	}

	public bool IsTEN_TRANG_THAI_LDNull() 
	{
		return pm_objDR.IsNull("TEN_TRANG_THAI_LD");
	}

	public void SetTEN_TRANG_THAI_LDNull() {
		pm_objDR["TEN_TRANG_THAI_LD"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_TRANG_THAI_LD 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_TRANG_THAI_LD", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_TRANG_THAI_LD"] = value;
		}
	}

	public bool IsID_LOAI_TRANG_THAI_LDNull()	{
		return pm_objDR.IsNull("ID_LOAI_TRANG_THAI_LD");
	}

	public void SetID_LOAI_TRANG_THAI_LDNull() {
		pm_objDR["ID_LOAI_TRANG_THAI_LD"] = System.Convert.DBNull;
	}

	public string strMA_TU_DIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_TU_DIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_TU_DIEN"] = value;
		}
	}

	public bool IsMA_TU_DIENNull() 
	{
		return pm_objDR.IsNull("MA_TU_DIEN");
	}

	public void SetMA_TU_DIENNull() {
		pm_objDR["MA_TU_DIEN"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_TU_DIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_TU_DIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_TU_DIEN"] = value;
		}
	}

	public bool IsID_LOAI_TU_DIENNull()	{
		return pm_objDR.IsNull("ID_LOAI_TU_DIEN");
	}

	public void SetID_LOAI_TU_DIENNull() {
		pm_objDR["ID_LOAI_TU_DIEN"] = System.Convert.DBNull;
	}

	public string strTEN_NGAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NGAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NGAN"] = value;
		}
	}

	public bool IsTEN_NGANNull() 
	{
		return pm_objDR.IsNull("TEN_NGAN");
	}

	public void SetTEN_NGANNull() {
		pm_objDR["TEN_NGAN"] = System.Convert.DBNull;
	}

	public string strTEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN"] = value;
		}
	}

	public bool IsTENNull() 
	{
		return pm_objDR.IsNull("TEN");
	}

	public void SetTENNull() {
		pm_objDR["TEN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_DM_TRANG_THAI_LAO_DONG() 
	{
		pm_objDS = new DS_V_DM_TRANG_THAI_LAO_DONG();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DM_TRANG_THAI_LAO_DONG(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DM_TRANG_THAI_LAO_DONG(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DM_TRANG_THAI_LAO_DONG();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
