///************************************************
/// Generated by: sonpt
/// Date: 03/03/2016 05:36:49
/// Goal: Create User Service Class for V_DM_DON_VI
///************************************************
/// <summary>
/// Create User Service Class for V_DM_DON_VI
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_V_DM_DON_VI : US_Object
{
	private const string c_TableName = "V_DM_DON_VI";
#region "Public Properties"
	public decimal dcID_DV_0 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DV_0", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DV_0"] = value;
		}
	}

	public bool IsID_DV_0Null()	{
		return pm_objDR.IsNull("ID_DV_0");
	}

	public void SetID_DV_0Null() {
		pm_objDR["ID_DV_0"] = System.Convert.DBNull;
	}

	public decimal dcID_DV_1 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DV_1", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DV_1"] = value;
		}
	}

	public bool IsID_DV_1Null()	{
		return pm_objDR.IsNull("ID_DV_1");
	}

	public void SetID_DV_1Null() {
		pm_objDR["ID_DV_1"] = System.Convert.DBNull;
	}

	public decimal dcID_DV_2 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DV_2", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DV_2"] = value;
		}
	}

	public bool IsID_DV_2Null()	{
		return pm_objDR.IsNull("ID_DV_2");
	}

	public void SetID_DV_2Null() {
		pm_objDR["ID_DV_2"] = System.Convert.DBNull;
	}

	public decimal dcID_DV_3 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DV_3", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DV_3"] = value;
		}
	}

	public bool IsID_DV_3Null()	{
		return pm_objDR.IsNull("ID_DV_3");
	}

	public void SetID_DV_3Null() {
		pm_objDR["ID_DV_3"] = System.Convert.DBNull;
	}

	public decimal dcID_DV_4 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DV_4", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DV_4"] = value;
		}
	}

	public bool IsID_DV_4Null()	{
		return pm_objDR.IsNull("ID_DV_4");
	}

	public void SetID_DV_4Null() {
		pm_objDR["ID_DV_4"] = System.Convert.DBNull;
	}

	public string strTEN_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DON_VI"] = value;
		}
	}

	public bool IsTEN_DON_VINull() 
	{
		return pm_objDR.IsNull("TEN_DON_VI");
	}

	public void SetTEN_DON_VINull() {
		pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
	}

	public string strExpr1 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "Expr1", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["Expr1"] = value;
		}
	}

	public bool IsExpr1Null() 
	{
		return pm_objDR.IsNull("Expr1");
	}

	public void SetExpr1Null() {
		pm_objDR["Expr1"] = System.Convert.DBNull;
	}

	public string strExpr2 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "Expr2", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["Expr2"] = value;
		}
	}

	public bool IsExpr2Null() 
	{
		return pm_objDR.IsNull("Expr2");
	}

	public void SetExpr2Null() {
		pm_objDR["Expr2"] = System.Convert.DBNull;
	}

	public string strExpr3 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "Expr3", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["Expr3"] = value;
		}
	}

	public bool IsExpr3Null() 
	{
		return pm_objDR.IsNull("Expr3");
	}

	public void SetExpr3Null() {
		pm_objDR["Expr3"] = System.Convert.DBNull;
	}

	public string strExpr4 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "Expr4", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["Expr4"] = value;
		}
	}

	public bool IsExpr4Null() 
	{
		return pm_objDR.IsNull("Expr4");
	}

	public void SetExpr4Null() {
		pm_objDR["Expr4"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_DM_DON_VI() 
	{
		pm_objDS = new DS_V_DM_DON_VI();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DM_DON_VI(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DM_DON_VI(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DM_DON_VI();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
