///************************************************
/// Generated by: haihd
/// Date: 17/08/2015 09:13:24
/// Goal: Create User Service Class for V_F320_LAP_HOP_DONG
///************************************************
/// <summary>
/// Create User Service Class for V_F320_LAP_HOP_DONG
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US
{

    public class US_V_F320_LAP_HOP_DONG : US_Object
    {
        private const string c_TableName = "V_F320_LAP_HOP_DONG";
        #region "Public Properties"
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public decimal dcID_NHAN_VIEN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NHAN_VIEN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NHAN_VIEN"] = value;
            }
        }

        public bool IsID_NHAN_VIENNull()
        {
            return pm_objDR.IsNull("ID_NHAN_VIEN");
        }

        public void SetID_NHAN_VIENNull()
        {
            pm_objDR["ID_NHAN_VIEN"] = System.Convert.DBNull;
        }

        public string strMA_NV
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_NV", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_NV"] = value;
            }
        }

        public bool IsMA_NVNull()
        {
            return pm_objDR.IsNull("MA_NV");
        }

        public void SetMA_NVNull()
        {
            pm_objDR["MA_NV"] = System.Convert.DBNull;
        }

        public string strHO_TEN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "HO_TEN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["HO_TEN"] = value;
            }
        }

        public bool IsHO_TENNull()
        {
            return pm_objDR.IsNull("HO_TEN");
        }

        public void SetHO_TENNull()
        {
            pm_objDR["HO_TEN"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_HOP_DONG
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_HOP_DONG", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_HOP_DONG"] = value;
            }
        }

        public bool IsID_LOAI_HOP_DONGNull()
        {
            return pm_objDR.IsNull("ID_LOAI_HOP_DONG");
        }

        public void SetID_LOAI_HOP_DONGNull()
        {
            pm_objDR["ID_LOAI_HOP_DONG"] = System.Convert.DBNull;
        }

        public string strLOAI_HOP_DONG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "LOAI_HOP_DONG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["LOAI_HOP_DONG"] = value;
            }
        }

        public bool IsLOAI_HOP_DONGNull()
        {
            return pm_objDR.IsNull("LOAI_HOP_DONG");
        }

        public void SetLOAI_HOP_DONGNull()
        {
            pm_objDR["LOAI_HOP_DONG"] = System.Convert.DBNull;
        }

        public string strMA_LOAI_HOP_DONG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_LOAI_HOP_DONG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_LOAI_HOP_DONG"] = value;
            }
        }

        public bool IsMA_LOAI_HOP_DONGNull()
        {
            return pm_objDR.IsNull("MA_LOAI_HOP_DONG");
        }

        public void SetMA_LOAI_HOP_DONGNull()
        {
            pm_objDR["MA_LOAI_HOP_DONG"] = System.Convert.DBNull;
        }

        public string strMA_HOP_DONG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_HOP_DONG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_HOP_DONG"] = value;
            }
        }

        public bool IsMA_HOP_DONGNull()
        {
            return pm_objDR.IsNull("MA_HOP_DONG");
        }

        public void SetMA_HOP_DONGNull()
        {
            pm_objDR["MA_HOP_DONG"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_BAT_DAU
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_BAT_DAU", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_BAT_DAU"] = value;
            }
        }

        public bool IsNGAY_BAT_DAUNull()
        {
            return pm_objDR.IsNull("NGAY_BAT_DAU");
        }

        public void SetNGAY_BAT_DAUNull()
        {
            pm_objDR["NGAY_BAT_DAU"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_KET_THUC
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_KET_THUC", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_KET_THUC"] = value;
            }
        }

        public bool IsNGAY_KET_THUCNull()
        {
            return pm_objDR.IsNull("NGAY_KET_THUC");
        }

        public void SetNGAY_KET_THUCNull()
        {
            pm_objDR["NGAY_KET_THUC"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_KY_HOP_DONG
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_KY_HOP_DONG", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_KY_HOP_DONG"] = value;
            }
        }

        public bool IsNGAY_KY_HOP_DONGNull()
        {
            return pm_objDR.IsNull("NGAY_KY_HOP_DONG");
        }

        public void SetNGAY_KY_HOP_DONGNull()
        {
            pm_objDR["NGAY_KY_HOP_DONG"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_LAP
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_LAP", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_LAP"] = value;
            }
        }

        public bool IsNGAY_LAPNull()
        {
            return pm_objDR.IsNull("NGAY_LAP");
        }

        public void SetNGAY_LAPNull()
        {
            pm_objDR["NGAY_LAP"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_SUA
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_SUA", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_SUA"] = value;
            }
        }

        public bool IsNGAY_SUANull()
        {
            return pm_objDR.IsNull("NGAY_SUA");
        }

        public void SetNGAY_SUANull()
        {
            pm_objDR["NGAY_SUA"] = System.Convert.DBNull;
        }

        public string strNGUOI_LAP
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_LAP", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_LAP"] = value;
            }
        }

        public bool IsNGUOI_LAPNull()
        {
            return pm_objDR.IsNull("NGUOI_LAP");
        }

        public void SetNGUOI_LAPNull()
        {
            pm_objDR["NGUOI_LAP"] = System.Convert.DBNull;
        }

        public string strNGUOI_SUA
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_SUA", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_SUA"] = value;
            }
        }

        public bool IsNGUOI_SUANull()
        {
            return pm_objDR.IsNull("NGUOI_SUA");
        }

        public void SetNGUOI_SUANull()
        {
            pm_objDR["NGUOI_SUA"] = System.Convert.DBNull;
        }

        public string strDA_XOA
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DA_XOA", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DA_XOA"] = value;
            }
        }

        public bool IsDA_XOANull()
        {
            return pm_objDR.IsNull("DA_XOA");
        }

        public void SetDA_XOANull()
        {
            pm_objDR["DA_XOA"] = System.Convert.DBNull;
        }

        #endregion
        #region "Init Functions"
        public US_V_F320_LAP_HOP_DONG()
        {
            pm_objDS = new DS_V_F320_LAP_HOP_DONG();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_V_F320_LAP_HOP_DONG(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_V_F320_LAP_HOP_DONG(decimal i_dbID)
        {
            pm_objDS = new DS_V_F320_LAP_HOP_DONG();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion

        public void FillDataset_by_ngay_hien_tai(DS_V_F320_LAP_HOP_DONG v_ds)
        {
            CStoredProc v_sp = new CStoredProc("pr_V_F320_LAP_HOP_DONG_by_date");
            
            v_sp.fillDataSetByCommand(this, v_ds);
        }

        public void FillDataset_by_ngay_hien_tai(DS_V_F320_LAP_HOP_DONG v_ds, decimal ip_dc_id_nhan_vien)
        {
            CStoredProc v_sp = new CStoredProc("pr_V_F320_LAP_HOP_DONG_by_id_nv_and_date");
            v_sp.addDecimalInputParam("@ip_dc_id_nhan_vien", ip_dc_id_nhan_vien);

            v_sp.fillDataSetByCommand(this, v_ds);
        }
    }
}
