///************************************************
/// Generated by: haihd
/// Date: 28/11/2015 03:02:04
/// Goal: Create User Service Class for V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN
///************************************************
/// <summary>
/// Create User Service Class for V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US
{

    public class US_V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN : US_Object
    {
        private const string c_TableName = "V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN";

        #region "Public Properties"
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public decimal dcID_NHAN_VIEN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_NHAN_VIEN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_NHAN_VIEN"] = value;
            }
        }

        public bool IsID_NHAN_VIENNull()
        {
            return pm_objDR.IsNull("ID_NHAN_VIEN");
        }

        public void SetID_NHAN_VIENNull()
        {
            pm_objDR["ID_NHAN_VIEN"] = System.Convert.DBNull;
        }

        public string strMA_NV
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_NV", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_NV"] = value;
            }
        }

        public bool IsMA_NVNull()
        {
            return pm_objDR.IsNull("MA_NV");
        }

        public void SetMA_NVNull()
        {
            pm_objDR["MA_NV"] = System.Convert.DBNull;
        }

        public string strHO_DEM
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "HO_DEM", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["HO_DEM"] = value;
            }
        }

        public bool IsHO_DEMNull()
        {
            return pm_objDR.IsNull("HO_DEM");
        }

        public void SetHO_DEMNull()
        {
            pm_objDR["HO_DEM"] = System.Convert.DBNull;
        }

        public string strTEN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN"] = value;
            }
        }

        public bool IsTENNull()
        {
            return pm_objDR.IsNull("TEN");
        }

        public void SetTENNull()
        {
            pm_objDR["TEN"] = System.Convert.DBNull;
        }

        public string strHO_TEN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "HO_TEN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["HO_TEN"] = value;
            }
        }

        public bool IsHO_TENNull()
        {
            return pm_objDR.IsNull("HO_TEN");
        }

        public void SetHO_TENNull()
        {
            pm_objDR["HO_TEN"] = System.Convert.DBNull;
        }

        public decimal dcID_PHU_CAP
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_PHU_CAP", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_PHU_CAP"] = value;
            }
        }

        public bool IsID_PHU_CAPNull()
        {
            return pm_objDR.IsNull("ID_PHU_CAP");
        }

        public void SetID_PHU_CAPNull()
        {
            pm_objDR["ID_PHU_CAP"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_PHU_CAP
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_PHU_CAP", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_PHU_CAP"] = value;
            }
        }

        public bool IsID_LOAI_PHU_CAPNull()
        {
            return pm_objDR.IsNull("ID_LOAI_PHU_CAP");
        }

        public void SetID_LOAI_PHU_CAPNull()
        {
            pm_objDR["ID_LOAI_PHU_CAP"] = System.Convert.DBNull;
        }

        public string strMA_TU_DIEN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_TU_DIEN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_TU_DIEN"] = value;
            }
        }

        public bool IsMA_TU_DIENNull()
        {
            return pm_objDR.IsNull("MA_TU_DIEN");
        }

        public void SetMA_TU_DIENNull()
        {
            pm_objDR["MA_TU_DIEN"] = System.Convert.DBNull;
        }

        public string strTEN_NGAN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_NGAN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_NGAN"] = value;
            }
        }

        public bool IsTEN_NGANNull()
        {
            return pm_objDR.IsNull("TEN_NGAN");
        }

        public void SetTEN_NGANNull()
        {
            pm_objDR["TEN_NGAN"] = System.Convert.DBNull;
        }

        public string strTEN_LOAI_PHU_CAP
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_LOAI_PHU_CAP", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_LOAI_PHU_CAP"] = value;
            }
        }

        public bool IsTEN_LOAI_PHU_CAPNull()
        {
            return pm_objDR.IsNull("TEN_LOAI_PHU_CAP");
        }

        public void SetTEN_LOAI_PHU_CAPNull()
        {
            pm_objDR["TEN_LOAI_PHU_CAP"] = System.Convert.DBNull;
        }

        public string strDOI_TUONG_HUONG_PHU_CAP
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DOI_TUONG_HUONG_PHU_CAP", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DOI_TUONG_HUONG_PHU_CAP"] = value;
            }
        }

        public bool IsDOI_TUONG_HUONG_PHU_CAPNull()
        {
            return pm_objDR.IsNull("DOI_TUONG_HUONG_PHU_CAP");
        }

        public void SetDOI_TUONG_HUONG_PHU_CAPNull()
        {
            pm_objDR["DOI_TUONG_HUONG_PHU_CAP"] = System.Convert.DBNull;
        }

        public decimal dcTI_LE
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "TI_LE", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["TI_LE"] = value;
            }
        }

        public bool IsTI_LENull()
        {
            return pm_objDR.IsNull("TI_LE");
        }

        public void SetTI_LENull()
        {
            pm_objDR["TI_LE"] = System.Convert.DBNull;
        }

        public decimal dcID_QUYET_DINH
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_QUYET_DINH", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_QUYET_DINH"] = value;
            }
        }

        public bool IsID_QUYET_DINHNull()
        {
            return pm_objDR.IsNull("ID_QUYET_DINH");
        }

        public void SetID_QUYET_DINHNull()
        {
            pm_objDR["ID_QUYET_DINH"] = System.Convert.DBNull;
        }

        public string strMA_QUYET_DINH
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_QUYET_DINH", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_QUYET_DINH"] = value;
            }
        }

        public bool IsMA_QUYET_DINHNull()
        {
            return pm_objDR.IsNull("MA_QUYET_DINH");
        }

        public void SetMA_QUYET_DINHNull()
        {
            pm_objDR["MA_QUYET_DINH"] = System.Convert.DBNull;
        }

        public string strTEN_NGAN_QUYET_DINH
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_NGAN_QUYET_DINH", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_NGAN_QUYET_DINH"] = value;
            }
        }

        public bool IsTEN_NGAN_QUYET_DINHNull()
        {
            return pm_objDR.IsNull("TEN_NGAN_QUYET_DINH");
        }

        public void SetTEN_NGAN_QUYET_DINHNull()
        {
            pm_objDR["TEN_NGAN_QUYET_DINH"] = System.Convert.DBNull;
        }

        public string strTEN_QUYET_DINH
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN_QUYET_DINH", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN_QUYET_DINH"] = value;
            }
        }

        public bool IsTEN_QUYET_DINHNull()
        {
            return pm_objDR.IsNull("TEN_QUYET_DINH");
        }

        public void SetTEN_QUYET_DINHNull()
        {
            pm_objDR["TEN_QUYET_DINH"] = System.Convert.DBNull;
        }

        public string strNGUOI_LAP
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_LAP", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_LAP"] = value;
            }
        }

        public bool IsNGUOI_LAPNull()
        {
            return pm_objDR.IsNull("NGUOI_LAP");
        }

        public void SetNGUOI_LAPNull()
        {
            pm_objDR["NGUOI_LAP"] = System.Convert.DBNull;
        }

        public string strNGUOI_SUA
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "NGUOI_SUA", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["NGUOI_SUA"] = value;
            }
        }

        public bool IsNGUOI_SUANull()
        {
            return pm_objDR.IsNull("NGUOI_SUA");
        }

        public void SetNGUOI_SUANull()
        {
            pm_objDR["NGUOI_SUA"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_LAP
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_LAP", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_LAP"] = value;
            }
        }

        public bool IsNGAY_LAPNull()
        {
            return pm_objDR.IsNull("NGAY_LAP");
        }

        public void SetNGAY_LAPNull()
        {
            pm_objDR["NGAY_LAP"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_SUA
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_SUA", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_SUA"] = value;
            }
        }

        public bool IsNGAY_SUANull()
        {
            return pm_objDR.IsNull("NGAY_SUA");
        }

        public void SetNGAY_SUANull()
        {
            pm_objDR["NGAY_SUA"] = System.Convert.DBNull;
        }

        public string strDA_XOA
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "DA_XOA", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["DA_XOA"] = value;
            }
        }

        public bool IsDA_XOANull()
        {
            return pm_objDR.IsNull("DA_XOA");
        }

        public void SetDA_XOANull()
        {
            pm_objDR["DA_XOA"] = System.Convert.DBNull;
        }

        #endregion

        #region "Init Functions"
        public US_V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN()
        {
            pm_objDS = new DS_V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN(decimal i_dbID)
        {
            pm_objDS = new DS_V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion

        public void FillDataset_by_id_nhan_vien(DS_V_F395_QUAN_LY_PHU_CAP_NHAN_VIEN op_ds_quan_ly_phu_cap_nhan_vien, decimal ip_dc_id_nhan_vien)
        {
            CStoredProc v_cstore = new CStoredProc("pr_lay_du_lieu_phu_cap_by_id_nhan_vien");

            v_cstore.addDecimalInputParam("@ip_dc_id_nhan_vien", ip_dc_id_nhan_vien);

            v_cstore.fillDataSetByCommand(this, op_ds_quan_ly_phu_cap_nhan_vien);
        }

    }
}
