//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_DichVuMatDat.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BKI_DVMDEntities : DbContext
    {
        public BKI_DVMDEntities()
            : base("name=BKI_DVMDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BACKUP_INFO> BACKUP_INFO { get; set; }
        public virtual DbSet<V_RPT_LUONG> V_RPT_LUONG { get; set; }
    }
}
