using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

using BKI_DichVuMatDat;
using BKI_DichVuMatDat.US;
using BKI_DichVuMatDat.DS;
using BKI_DichVuMatDat.DS.CDBNames;
using IP.Core.IPCommon;
using System.Globalization;
using DevExpress.XtraEditors;
using IP.Core.IPSystemAdmin;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid;

namespace BKI_DichVuMatDat.BaoCao
{
    public partial class F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY : Form
    {
        public F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY()
        {
            InitializeComponent();
            format_controll();
            // This line of code is generated by Data Source Configuration Wizard
            //v_F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TYTableAdapter1.Fill(dS_V_F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY1.V_F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY);
        }


        
        #region interface
        #endregion
        
        #region members
        int so_lao_dong = 0;
        int summaryColumnID = -1;
        #endregion

        #region private methods

        private void format_controll()
        {
            CenterToScreen();
            set_define_events();
        }

        private void set_init_form_load()
        {
            m_dat_thang.EditValue = DateTime.Now;
        }

        private void load_data_2_grid()
        {
            
            US_V_F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY v_us = new US_V_F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY();
            DataSet v_ds = new DataSet();
            v_ds.Tables.Add();

            v_us.load_du_lieu_nhan_vien_hoat_dong(v_ds, m_dat_thang.DateTime.Date);
            m_grc_v_nhan_vien_dang_hoat_dong.DataSource = null;
            m_grc_v_nhan_vien_dang_hoat_dong.DataSource = v_ds.Tables[0];
            make_stt(m_grv_v_nhan_vien_dang_hoat_dong);
        }

        private void make_stt(GridView ip_grv)
        {
            var col = ip_grv.Columns.Add();
            col.FieldName = "STT";
            col.Caption = "STT";
            col.UnboundType = DevExpress.Data.UnboundColumnType.Integer;
            ip_grv.CustomUnboundColumnData += ip_grv_CustomUnboundColumnData;
        }

        private void ip_grv_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            if (e.IsGetData)
                e.Value = e.ListSourceRowIndex + 1;
        }

        #endregion

        //
        //
        //EVENTS
        //
        //

        private void set_define_events()
        {
            m_cmd_view.Click += M_cmd_view_Click;
            m_dat_thang.EditValueChanged += M_dat_thang_EditValueChanged;
            this.Load += F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY_Load;
            m_cmd_xuat_excel.Click += M_cmd_xuat_excel_Click;
            this.m_grv_v_nhan_vien_dang_hoat_dong.CustomSummaryCalculate += new DevExpress.Data.CustomSummaryEventHandler(this.m_grv_v_nhan_vien_dang_hoat_dong_CustomSummaryCalculate);
        }

        void m_grv_v_nhan_vien_dang_hoat_dong_CustomSummaryCalculate(object sender, DevExpress.Data.CustomSummaryEventArgs e)
        {
            try
            {
                GridView view = sender as GridView;
                summaryColumnID = Convert.ToInt16((e.Item as GridGroupSummaryItem).Tag);

                if (e.SummaryProcess == DevExpress.Data.CustomSummaryProcess.Start)
                {
                    so_lao_dong = 0;
                }
                if (e.SummaryProcess == DevExpress.Data.CustomSummaryProcess.Calculate)
                {
                    switch (summaryColumnID)
                    {
                        case 1:
                            so_lao_dong++;
                            break;
                    }
                }
                if (e.SummaryProcess == DevExpress.Data.CustomSummaryProcess.Finalize)
                {
                    switch (summaryColumnID)
                    {
                        case 1:
                            e.TotalValue = so_lao_dong;
                            break;
                    }
                }
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void M_cmd_xuat_excel_Click(object sender, EventArgs e)
        {
            try
            {
                SaveFileDialog saveFileDialog1 = new SaveFileDialog();
                saveFileDialog1.Filter = "xls files (*.xls)|*.xls|All files (*.*)|*.*";
                saveFileDialog1.RestoreDirectory = true;
                if (saveFileDialog1.ShowDialog() == DialogResult.OK)
                {
                    m_grc_v_nhan_vien_dang_hoat_dong.ExportToXls(saveFileDialog1.FileName);
                    CHRM_BaseMessages.MsgBox_Infor(CONST_ID_MSGBOX.INFOR_LUU_BAO_CAO_THANH_CONG);
                }
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void M_cmd_view_Click(object sender, EventArgs e)
        {
            try
            {
                load_data_2_grid();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void M_dat_thang_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                //load_data_2_grid();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void F460_DANH_SACH_NHAN_VIEN_DANG_HOAT_DONG_O_CONG_TY_Load(object sender, EventArgs e)
        {
            try
            {
                set_init_form_load();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }
    }
}
